### ISSUE TITLE
get_users_by_usernames should be POST and not GET

### ISSUE THREAD

**Issue by towolf** [Vaelor/python-mattermost-driver#11]
This here is the wrong method:

https://github.com/Vaelor/python-mattermost-driver/blob/940cf652cd2af438e55c62cef357e63b99dfefca/src/mattermostdriver/endpoints/users.py#L26

Not worth doing a PR for?

**Comment by Vaelor** [comment]
You are right, thanks!

**Comment by Vaelor** [comment]
Should be available in the new version 2.1.3 on pypi
