### ISSUE TITLE
Python 2.7 support

### ISSUE THREAD

**Issue by dan-klasson** [Vaelor/python-mattermost-driver#20]
I'm getting this when trying to install it with pip on Python 2.7:

    Collecting mattermostdriver
      Using cached mattermostdriver-4.2.0.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-build-hV1oTl/mattermostdriver/setup.py", line 11, in <module>
            with open(readme_file, encoding='utf-8') as f:
        TypeError: 'encoding' is an invalid keyword argument for this function

Will this library not support 2.7?

**Comment by Vaelor** [comment]
I honestly haven't tried it - I haven't used Python 2 for, I don't know, ages.
Have to check when I get home if it does run.
I saw that you made two PRs for fixing the setup.py - have you tried running it with Python 2, does it work?

**Comment by Vaelor** [comment]
Having a quick look, I don't think this will work on 2.7...
I use asyncio, which AFAIK won't work on python 2,7 (If I recall correctly, the websockets library does only work on python 3 also), so that probably would not work, even if you could install it..

**Comment by Vaelor** [comment]
Since I am pretty sure that it won't work with 2.7 and (at least I) won't include support for it, I would like to close this for now.
