### ISSUE TITLE
Create User Access Token

### ISSUE THREAD

**Issue by ryuuji5** [Vaelor/python-mattermost-driver#23]
Mattermost API has 'Create a user access token' POST request menu.
Would you update python-mattermost-driver for this function??

I'm trying to post "create user access token" request like below. But, it doesn't work.
Do you have any idea ? 
My mattermost server is version 4.6 .

/* MY CODE FOR POST REQUEST  */
payload={"description": "some message"}

requests(
    'https://<my_mattermost_URL>/api/v4/users/UserID from API/tokens',
    cookies = foo.client.cookise,
    json = payload
)
/* END OF CODE */

If you know something about this problem, please help me...

* API Doc
https://api.mattermost.com/#tag/users%2Fpaths%2F~1users~1%7Buser_id%7D~1tokens%2Fpost

**Comment by ryuuji5** [comment]
I get response like below
"""
{"id":"api.context.session_expired.app_error","message":"Invalid or expired session, please login again.","detailed_error":"","request_id":"<some hash>","status_code":401}
"""

**Comment by Vaelor** [comment]
Thanks, I forgot that somehow!

In your request `/api/v4/users//tokens` You seem to be missing the `user_id`
`/api/v4/users/{user_id}/tokens`
(Not 100% sure, but if you want to create a token for your user, probably `/api/v4/users/me/tokens` works)

The response you get, indicates that you are missing your token (you get one from the server when you login) in your request. this library takes care of that everytime a request is run.
If you would want to do that manually you need to do include it in the header:
``` python
# Assuming you set up the mattermostdriver somewhere
foo = Driver({})
foo.login() # After this, the token is saved in `Driver.client.token`
requests(
'https://<my_mattermost_URL>/api/v4/users//tokens',
    # This is needed so mattermost knows you are allowed to do that 
    header={"Authorization": "Bearer {token:s}".format(token=foo.client.token)
    # Not sure about the cookie stuff you are doing
    cookies=foo.client.cookise,
    json=payload
)
```

But with the version I just released (4.3.1) you can just do
`foo.users.create_user_access_token('user_id', options=payload)`
and should be fine too.
Let me know if this fixed your problem!

**Comment by ryuuji5** [comment]
It worked manually thanks to your advice : )

And I also could use the function `foo.users.create_user_access_token('user_id', options=payload)`

Thank you!

**Comment by Vaelor** [comment]
Glad to hear :-)
