### ISSUE TITLE
Update Configuration API

### ISSUE THREAD

**Issue by ryuuji5** [Vaelor/python-mattermost-driver#24]
Thank you for helping me for creating access token.

By the way, I also want to use update configuration API like below.
https://api.mattermost.com/#tag/system%2Fpaths%2F~1config%2Fget

According to the documentation, update_conf API needs argument including new configuration(json type).

But, it looks like that your "update_configuration" fuction doesn't have any argument.
How to use it ??
https://github.com/Vaelor/python-mattermost-driver/blob/a7628e8d383cbd0ba90bc1a84257ade33d837263/src/mattermostdriver/endpoints/system.py#L29-L32

Thank you.

**Comment by Vaelor** [comment]
Damn, you found another bug... :-D
Will be fixed today, sorry for the inconvenience!

**Comment by Vaelor** [comment]
Currently unsure, the mattermost API is missing a parameter there itself. I assume they want a whole config as json there. Can't guarantee that though, but will make a commit later to try and fix that.

**Comment by ryuuji5** [comment]
Yes. The document shows example only about Go.

I tried to use API manually, and it worked!! Like this.
`
config_content = "get config somehow (load conf.json or use get configuration API)"
request.put(
    MattermostURL
    headers = {"Authorization": "Bearer {token:s}".format(token=foo.client.token)},
    cookies = foo.client.cookies,
    json = config_content
)
`

Please reference it : )

**Comment by Vaelor** [comment]
Thank you so much for trying that out!
I just uploaded a 4.3.2 version which takes `options` (the config_content)
I probably should rename options to json someday... :-D Somehow that sounds more clear.

Well, thanks :-) Let me know if you have any other issues, I am glad if someone reports the bugs :-)

**Comment by ryuuji5** [comment]
Thank you for your fixing quickly!!

I want to help you by sending pull request. But I cannot do this because of my company circumstances actually... : (

I hope this driver to be a good one : )
If I can, I will make some commitment in my house : )

thank you.
