### ISSUE TITLE
missing '/' 

### ISSUE THREAD

**Issue by dlahlou** [Vaelor/python-mattermost-driver#27]
Thank you for your excellent job.
There is a missing '/' in this line : https://github.com/Vaelor/python-mattermost-driver/blob/master/src/mattermostdriver/endpoints/users.py#L203 between `self.endpoint` and `user_id`.

**Comment by Vaelor** [comment]
Fixed it, not sure if I get to release a new fix version today. Will try ASAP (currently a bit short on time)

**Comment by Vaelor** [comment]
And thanks for reporting it :-) !

**Comment by dlahlou** [comment]
Thank you. We'll be waiting for the release :)

**Comment by Vaelor** [comment]
I released the fix in a 4.5.0 version - I never got around to releasing the changes for mattermost 4.8, so these are in there to. Let me know if you stumble upon any issues!
