### ISSUE TITLE
Driver cannot update channel if user is not in this channel

### ISSUE THREAD

**Issue by artempronevskiy** [Vaelor/python-mattermost-driver#28]
Driver cannot update channel if user (whose token is used for authorization) is not in this channel. Server sends 404 status code for `self.driver.channels.update_channel` method.

```
  File "/usr/local/lib/python3.5/dist-packages/mattermostdriver/endpoints/channels.py", line 45, in update_channel
    options=options
  File "/usr/local/lib/python3.5/dist-packages/mattermostdriver/client.py", line 172, in put
    return self.make_request('put', endpoint, options=options, params=params, data=data).json()
  File "/usr/local/lib/python3.5/dist-packages/mattermostdriver/client.py", line 140, in make_request
    response.raise_for_status()
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 829, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found
```

**Comment by artempronevskiy** [comment]
And I'm not sure (didn't test it yet) if this is general mattermost api limitation or just limitation of "token only" auth method

**Comment by Vaelor** [comment]
Mhh I suspect a limitation in mattermost in this case. I am currently a bit short on time, but I will update the driver for mattermost 5.0 in the next days and have a look at it this then! Thanks for reporting it!

**Comment by Vaelor** [comment]
@artempronevskiy I suppose the user/token is some kind of admin (system admin/team admin) in mattermost? If not, you should try that out.
Also, if the channel is a private channel and the user is not a member, AFAIK he can't do anything (not even join the channel himself, if I remember correctly)

**Comment by artempronevskiy** [comment]
@Vaelor I use token that's related to mattermost system admin and I'm trying to handle public channels

**Comment by artempronevskiy** [comment]
Btw, the workaround is to add user to every channel to be edited before editing them using, using the corresponding api call...

**Comment by Vaelor** [comment]
https://api.mattermost.com/#tag/channels%2Fpaths%2F~1channels~1{channel_id}%2Fput sounds to me like it 'should' be possible (the permission is AFAIK only a enterprise feature, so in Team Edition I guess it works always) - and I don't see any hint that the user triggering the api call has to be in the channel.
I asked in the official Mattermost chat if this is intended or not.

**Comment by Vaelor** [comment]
Just a heads up, I got a response saying for channel members or system admins it should be possible.
Tried your case out mysel and I can reproduce it as system admin and not being in the channel. So it seems to be a bug on their end. Will keep this one open until we know for certain.

**Comment by artempronevskiy** [comment]
Got it. Thanks!

**Comment by Vaelor** [comment]
@artempronevskiy It seems 5.1 fixed this, at least the mattermost team couldn't reproduce the issue and in my case it worked now too! Please check if you have the time!
