### ISSUE TITLE
Compliance.Create_Report Method Doesn't Take Data Variables

### ISSUE THREAD

**Issue by KavanMally** [Vaelor/python-mattermost-driver#39]
I am trying to create a compliance report via this project through compliance.py->create_report(). I have been able to create a Driver object, login, and run other commands in users.py and the get_reports method. Looking through the documentation [here](https://docs.mattermost.com/administration/ediscovery.html), mattermost is expecting data variables to specify how the report should be created such as time range of compliance report and description. However, the create_report method doesn't take any parameters and trying to pass any variables into it will throw a parameter error due to its method signature not allowing for them. Trying to run the method as is will raise InvalidOrMissingParameters(message):Invalid description. 

I have tested that the [endpoint](https://api.mattermost.com/#tag/compliance) works on my server, I ran curl commands as specified in the documentation above and was able to see new reports created when running the get_reports method.

**Comment by Vaelor** [comment]
Hey! Sorry for your issue. I will try to have a look at it, but I am currently on holiday, so it may take a few days.

I guess, I forgot to add the parameters or maybe they got added later on and I missed them.

**Comment by Vaelor** [comment]
@KavanMally It seems that their api documentation is incomplete in this area.

I am not a 100% sure, since I can't test it (no enterprise license) but I believe I fixed it.
Maybe you could verify it on your end?
