### ISSUE TITLE
Configurable timeouts

### ISSUE THREAD

**Issue by backbord** [Vaelor/python-mattermost-driver#40]
Hi,

thanks for this awesome package!

My network isn't very reliable so I'd love to be able to set sensible [timeouts](https://2.python-requests.org/en/master/user/advanced/#timeouts) for the requests made using `requests.get` (to be used in the [client](https://github.com/Vaelor/python-mattermost-driver/blob/master/src/mattermostdriver/client.py#L132-L140) for example).

Thanks and best regards!

**Comment by urbanonymous** [comment]
I might do it, it's a nice feature

**Comment by Vaelor** [comment]
Sounds good, it would be good to have that.
