### ISSUE TITLE
I'ts not posible add users with python driver when channel it's created from python driver

### ISSUE THREAD

**Issue by blanxart55** [Vaelor/python-mattermost-driver#47]
when i create a new channel from function mattermost_connection.channels.create_channel in python driver, the channel it's create correcly, but qhen i add user from function mattermost_connection.channels.add_user, the user not add in channel (the user i'ts in the team previously) 

when add a new user from mattermost web, the number of members counter plus the "gost user add from python driver", when refresh the page, the "gost user add from python driver" i'ts less

i try to set the mattermost_connection.channels.update_channel_roles, but not work.

when i talk about counter, i'ts the "members" counter in the top of chat

**Comment by Vaelor** [comment]
@blanxart55 Thank you for reporting your issue!
I will have a look at it and sorry for the delay.

Could you confirm if I understand you correctly?
 - If you create a user with this project, the user does exist afterwards
 - If the user is in the team and you add the user to the channel with this project, the user is not added to the channel
 - There is a counter that is increased, but no member is added in the 'members view'
