### ISSUE TITLE
Client._auth() -> TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by macher91** [Vaelor/python-mattermost-driver#49]
There is a bug after last update. There is no way to use token auth.
In client.py:
```
def auth_header(self):
    if self._auth: return None
...
```
then:
```
    def make_request(self, method, endpoint, options=None, params=None, data=None,  files=None, basepath=None):
...
    response = request(
        url + endpoint,
        headers=self.auth_header(),
        auth = self._auth(),
        verify=self._verify,
        json=options,
        params=params,
        data=data,
        files=files,
        timeout=self.request_timeout
    )
```
So if you want use token self_auth should be None. But then None will call...

**Comment by Vaelor** [comment]
Hi! Really sorry about that, I missed that when I was trying the last PR. :-( That's what I get for not yet having an automated test environment....

I will have it fixed in a moment.

**Comment by Vaelor** [comment]
@macher91 I just release 6.3.1 which fixes your issue. Thanks for reporting, I am sorry if I caused any problems!
