### ISSUE TITLE
Possible API improvements

### ISSUE THREAD

**Issue by sscherfke** [Vaelor/python-mattermost-driver#5]
I like that you divided mm-driver’s functionality into several classes that we can compose and customize.

However, I think that the actual usage of the diver when calling the enpoint’s methods could be improved, so that instead of doing

```python
mm = Driver(...)
mm.login()
mm.api['users'].get_user_by_username('another.name')
```
we can just do:

```python
mm = MatterMost(...)
mm.login()
mm.users.get_user_by_username('another.name')
```

This is relatively easy to implement in another wrapper class (maybe it can even be merged into `Driver`):
```python
class MatterMost:
    def __init__(self):
        self._driver = Driver()
        # self._driver.login()

    @property
    def userid(self):
        return self._driver.client.userid

    @property
    def username(self):
        return self._driver.client.username

    def __getattr__(self, key):
        try:
            return self._driver.api[key]
        except KeyError:
            raise AttributeError(key) from None
```

@Vaelor What do you think about this?

**Comment by Vaelor** [comment]
Hey! Sorry for the late and short reply! :-D
Yes, that sounds like a great idea. A wrapper is maybe not a bad idea, I do like that stuff like  `userid`, `username` belongs to `Mattermost` - I guess it would improve autocompletion, too?

**Comment by sscherfke** [comment]
Autocompletion for what exactly?

But maybe we can improve auto-completion (at least for interactive session) by explicitly setting the API endpoints as attributes instead of looking them up dynamically:
```python
class MatterMost:
    def __init__(self):
        self._driver = Driver()
        # self._driver.login()  # Useful for us, but maybe not for other users
        for k, v in self._driver.api.items():
            assert not hasattr(self, k)
            setattr(self, k, v)

    @property
    def userid(self):
        return self._driver.client.userid

    @property
    def username(self):
        return self._driver.client.username

```

**Comment by sscherfke** [comment]
On the other hand, `pylint` will not complain about missing attributes in the `__getattr_` variant, but in the `setattr()` variant, because it's not clever enough (and probably, it can’t) to find out which attributes I set in `__init__()`.

**Comment by Vaelor** [comment]
Well I like it either way. If autocompletion improves it is a nice plus, but not having to do `api['users']` would be very nice in every case :-D If you want to implement it, go ahead. I currently have a lot of work at my paid workplace so I wouldn't get to it before mid september.
