### ISSUE TITLE
Driver provides SSL context to ws:// URI scheme

### ISSUE THREAD

**Issue by oskapt** [Vaelor/python-mattermost-driver#6]
Connecting to an HTTP endpoint correctly sets `ws://` but incorrectly provides `ssl=context` with `context` being set on line 26 of `websocket.py`
```
context = ssl.create_default_context(purpose=ssl.Purpose.CLIENT_AUTH)
```

This is used on line 39, even if the URI scheme was set to `ws://` on line 32.

Setting `context=None` correctly resolves this.

(Before you ask why I'm using HTTP instead of HTTPS, I have the bot running within an overlay network under Rancher in AWS, so it communicates locally to Mattermost. If I provide the HTTPS URL for mattermost, it will exit the VPC and connect to the public IP for the load balancer, generating unnecessary usage charges. I terminate SSL on the load balancer, so I need internal communication to be unencrypted.)

**Comment by Vaelor** [comment]
Fixed with merge.
