### ISSUE TITLE
Passing a SSL Cert to the requests library

### ISSUE THREAD

**Issue by williehallock802** [Vaelor/python-mattermost-driver#64]
The following code works just fine in Jupyter:

```
from mattermostdriver import Driver
from pprint import pprint

options = {}

options[ 'url' ]   = '<url>'
options[ 'token' ] = '<your personal token here>'
options[ 'port' ]  = 443

%env REQUESTS_CA_BUNDLE=/path/to/cert.pem

driver = Driver( options = options )
driver.login()

teamData    = driver.teams.get_team_by_name( 'teamname' )
teamID      = teamData[ 'id' ]
channelData = driver.channels.get_channel_by_name( teamID, 'roomname' )

postOptions = { 'channel_id': channelData[ 'id' ], 'message': 'mattermost test' }

driver.posts.create_post( options = postOptions )
```

The reason why it works is that I can specify in the environment that path to the .pem file for the requests library to use. It would be nice if there was some way to pass this path directly down to the requests library through login() or just adding stuff to the options variable, but that does not appear to be possible...unless I have missed something.

**Comment by Vaelor** [comment]
Hi, can you try to set the `verify` option to the path of your CA (.pem)?
Verify can either be True or False or a path, which should do what you want.

My documentation is clearly missing that here though!

**Comment by williehallock802** [comment]
Yep, that worked. It would make for a good usage example for your documentation as it will likely be a fairly common case.

**Comment by dmpe** [comment]
haha, doc is still missing. the description says that it is either true or false
@Vaelor

**Comment by Vaelor** [comment]
Oh damn xD
