### ISSUE TITLE
The integration_actions endpoint is not implemented

### ISSUE THREAD

**Issue by rittelle** [Vaelor/python-mattermost-driver#67]
The API endpoints documented [here](https://api.mattermost.com/#tag/integration_actions) are not implemented (in version 7.0.1 at least).
I'll have a go at it if I figure out, how to use a forked package in my venv :)

**Comment by Vaelor** [comment]
Hi, thanks for reporting!
I will try to update them asap.

**Comment by rittelle** [comment]
Thanks for the response!
I've implemented them myself (didn't seem too difficult ;) ) a few minutes ago.

**Comment by Vaelor** [comment]
Released in 7.1.0
