### ISSUE TITLE
Get posts around oldest unread

### ISSUE THREAD

**Issue by trevormalloy** [Vaelor/python-mattermost-driver#76]
I cant seem to find a function that does this API call.
https://api.mattermost.com/#tag/posts/paths/~1users~1{user_id}~1channels~1{channel_id}~1posts~1unread/get

looking at the source code something like the code below would work in `mattermostdriver.endpoints.posts`
```
def get_unread_posts_for_channel(self, user_id, channel_id, params=None):
        return self.client.get(
            Users.endpoint + '/' + user_id + '/' + Channels.endpoint + '/' + channel_id + '/posts/unread',
            params=params
)
```
I can open a PR if needed, just wanted to post an issue first to see if maybe I am missing a function that already accomplishes this.

Cheers

**Comment by Vaelor** [comment]
Hi @trevormalloy - That endpoint is currently missing, if you want to create it and make a PR, I would be happy to merge it.
Sorry for the late response, life is getting in the way a lot :-D
