### ISSUE TITLE
Add support for OAuth token usage

### ISSUE THREAD

**Issue by linkmauve** [Vaelor/python-mattermost-driver#8]
This package currently requires a password for login, it should instead allow for OAuth token to be provided.

See also https://docs.mattermost.com/developer/personal-access-tokens.html

**Comment by Vaelor** [comment]
Yes, that has to be done. I already had a look at it and it seems to be easily integrated, I do plan to include this in the next release.

**Comment by Vaelor** [comment]
@linkmauve Please have a look at the new 2.2.0 version if it fixes this issue for you.

**Comment by Vaelor** [comment]
Assuming it works like expected, at least in my case. Please reopen if not ;-)
