### ISSUE TITLE
Driver.disconnect not working

### ISSUE THREAD

**Issue by wonsungkang** [Vaelor/python-mattermost-driver#91]
I found bug.

Bug fixed code is as follows
[disconnect_bug.txt](https://github.com/Vaelor/python-mattermost-driver/files/6588751/disconnect_bug.txt)

https://github.com/Vaelor/python-mattermost-driver/pull/92/files

**Comment by Vaelor** [comment]
Hi, thanks for your report! I will check it out and merge as soon as I had a look at it!

**Comment by fried** [comment]
This is resolved
